---
 render-dir: "/Users/riyakumari/Desktop/world-gen/render/" # required
 blend-filepath: "/Users/riyakumari/Desktop/world-gen/test.blend" # required
 render-engine: "CYCLES" # required, choose from BLENDER_EEVEE, or CYCLES
 image-resolution: [1024, 1024, 3]
 scene-coordinates: [-122.39622,37.79148,-122.38925,37.79431]
 outputs: ["depth", "flow"]
 is_suburbs:
 weather:
   - midday
   - noFog  
 class-names: ["Trees", "StreetLamps", "TwinBenches", "buildings", "roads", "Terrain", "buildings"]